<a href="https://colab.research.google.com/github/youngchae64/AIProject/blob/main/3%EC%A3%BC%EC%B0%A8_%EB%AF%B8%EC%85%98_%EC%86%94%EB%A3%A8%EC%85%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1.무작위의 데이터를 가 진 5x3의 행렬을 가지는 numpy array와 3x2 행렬을 가지는 numpy array를 만든 후 행열곱 연산을 진행해보세요

In [51]:
import numpy as np

In [52]:
arr1 = np.random.random((5,3))
arr2 = np.random.random((3,2))

In [53]:
arr1

array([[0.52099273, 0.53841174, 0.55489275],
       [0.54009996, 0.37501279, 0.98629106],
       [0.69967441, 0.11620764, 0.72232236],
       [0.94467983, 0.19982419, 0.95211183],
       [0.60849952, 0.43720359, 0.71084533]])

In [54]:
arr2

array([[0.47696504, 0.11145455],
       [0.46982396, 0.83249932],
       [0.97948309, 0.36745681]])

In [55]:
dot = print(arr1@arr2)

[[1.04496211 0.71019354]
 [1.39985421 0.73481386]
 [1.09581991 0.44014695]
 [1.47703888 0.62150235]
 [1.1919027  0.69299669]]


Q2. Numpy에서 사용하는 2개의 numpy array가 있을때, 두 numpy array의 concatenate 연산을 수행해보세요


In [56]:
arr1 = np.array([[5,7], [9,11]], float)
arr2 = np.array([[2,4], [6,8]], float)

In [57]:
concat_1 = np.concatenate((arr1,arr2), axis=0)
concat_1

array([[ 5.,  7.],
       [ 9., 11.],
       [ 2.,  4.],
       [ 6.,  8.]])

In [58]:
concat_2 = np.concatenate((arr1,arr2), axis=1)
concat_2

array([[ 5.,  7.,  2.,  4.],
       [ 9., 11.,  6.,  8.]])

Q3. 아래와 같이 데이터가 주어져있을 때, 경사하강법을 위한 데이터를 분리해보세요.

주어진 xy 데이터를 이용해서 학습과 정답 데이터를 준비해보세요.

*추가 수정* 문제에서 주어진 xy에서 대괄호를 한 번 더 묶어주어야 문제 해결이 가능합니다.
(차원 관련)  (np.array([[1., 2., 3., 4., 5., 6.], [10., 20., 30., 40., 50., 60.]])

In [59]:
xy = np.array([[1.,2.,3.,4.,5.,6.], 
              [10., 20., 30., 40., 50., 60.]])

In [60]:
x_train = np.array(xy).flatten()
x_train = x_train[0:6]
print(x_train)

[1. 2. 3. 4. 5. 6.]


In [61]:
y_train = np.array(xy).flatten()
y_train = y_train[6:13]
print(y_train)

[10. 20. 30. 40. 50. 60.]


In [62]:
print(x_train,x_train.shape)
print(y_train,y_train.shape)

[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


Q.4  경사 하강법 구현을 위해서 위에서 분리한 x_train 데이터와 계산될 weight, bias 값을 정의해보세요. 여기서 구현한 weight와 bias 는 linear regression 계산을 진행할시 직선의 기울기와 y 절편의 값이 됩니다.

numpy 내의 random 함수를 이용해보세요.

In [63]:
beta_gd = np.random.rand()
bias = np.random.rand()

In [64]:
print(beta_gd)
print(bias)

0.25827570205868755
0.8059137939394458


Q5.  linear regression을 경사하강법으로 학습하는 코드를 구현해봅시다. 경사하강법 구현을 위한 학습 Loop를 구현해보세요. 최종적으로 1000회 반복했을 시에 결과를 출력하세요. 

단, Error는 차이의 제곱을 이용해서 계산해주세요.

Gradient 값은 우리가 예측하는 각 변수에 대한 미분값입니다.

In [65]:
xy = np.array([[1.,2.,3.,4.,5.,6.,],
               [3.,6.,9.,12.,15.,18.]])

In [66]:
print(x_train)
print(y_train)
print(beta_gd)
print(bias)

[1. 2. 3. 4. 5. 6.]
[10. 20. 30. 40. 50. 60.]
0.25827570205868755
0.8059137939394458


In [67]:
learning_rate = 0.01

In [71]:
for i in range(1000):
  error = y_train - x_train* beta_gd
  grad = -np.transpose(x_train) * error
  beta_gd = beta_gd - learning_rate*grad 

  if i % 100 == 0:
    print("error:", error)
    #print('Epoch([:10d/1000] error:[:10f], beta_gd:[:10f], bias:[:10f]'.format(i, error ,beta_gd.item(), bias.item()))

error: [4.16356766e-04 4.26325641e-14 2.84217094e-14 2.13162821e-14
 1.42108547e-14 1.42108547e-14]
error: [1.52400042e-04 4.26325641e-14 2.84217094e-14 2.13162821e-14
 1.42108547e-14 1.42108547e-14]
error: [5.57833441e-05 4.26325641e-14 2.84217094e-14 2.13162821e-14
 1.42108547e-14 1.42108547e-14]
error: [2.04185080e-05 4.26325641e-14 2.84217094e-14 2.13162821e-14
 1.42108547e-14 1.42108547e-14]
error: [7.47383431e-06 4.26325641e-14 2.84217094e-14 2.13162821e-14
 1.42108547e-14 1.42108547e-14]
error: [2.73566507e-06 4.26325641e-14 2.84217094e-14 2.13162821e-14
 1.42108547e-14 1.42108547e-14]
error: [1.00134189e-06 4.26325641e-14 2.84217094e-14 2.13162821e-14
 1.42108547e-14 1.42108547e-14]
error: [3.66523519e-07 4.26325641e-14 2.84217094e-14 2.13162821e-14
 1.42108547e-14 1.42108547e-14]
error: [1.34159466e-07 4.26325641e-14 2.84217094e-14 2.13162821e-14
 1.42108547e-14 1.42108547e-14]
error: [4.91067045e-08 4.26325641e-14 2.84217094e-14 2.13162821e-14
 1.42108547e-14 1.42108547e-14]
