<a href="https://colab.research.google.com/github/youngchae64/AIProject/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np

In [2]:
test_array = np.array([1,4,5,8], float)
test_array

array([1., 4., 5., 8.])

In [3]:
a = [[1,2,3,4],[3,4,5,6]]
a

[[1, 2, 3, 4], [3, 4, 5, 6]]

In [4]:
b = a

In [5]:
b

[[1, 2, 3, 4], [3, 4, 5, 6]]

In [6]:
a[0][0] =5

In [7]:
b

[[5, 2, 3, 4], [3, 4, 5, 6]]

In [8]:
test_array.dtype # 배열 전체의 데이터 타입을 반환함 

dtype('float64')

In [10]:
test_array.shape #배열의 shape을 반환함 

(4,)

In [11]:
test_matrix = [[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [12]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [13]:
np.array(test_matrix).reshape(-1,2).shape
# -1: size를 기반으로 row 개수를 자동으로 생성 

(4, 2)

In [15]:
#flatten: 다차원의 array를 1차원으로 반환해주는 함수 
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8])

In [16]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)

In [17]:
a[:2:] #전체 row의 2열 이상

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
a[1,1:3] # 1 row의 1~2열 

array([7, 8])

In [19]:
a[1:3] #1row ~ 2row의 전체

array([[ 6,  7,  8,  9, 10]])

In [24]:
np.arange(30).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [25]:
np.arange(0,5,0.5) #np에서는 float단위로 띄울수 있음

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [26]:
np.zeros(shape =(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [27]:
np.zeros((2,5)) # 2 by 5 - zero matrix 생성

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
#eye: 대각선이 1인 행렬, k 값의 시작 index가 변경 가능
np.eye(N =3, M=5, dtype = np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.eye(3,5, k = 2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
#diag: 대각 행렬의 값을 추출함 
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [35]:
test_array = np.arange(1,11)
test_array.sum()

55

In [36]:
#모든 operation function을 실행할때, 기준이 되는 dimension 축, axis = 1
#새로생기는 축이 axis = 0이 된다. 기존에 존재하던 축은 axis =1 
test_array = np.arange(1,13).reshape(3,4)

In [37]:
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
test_array.sum(axis = 1), test_array.sum(axis = 0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [39]:
#broadcasting: numpy는 shape이 다른 배열 간 연산을 지원한다 
test_matrix = np.array([[1,2,3], [4,5,6]], float)
scalar = 3

In [40]:
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [42]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [44]:
np.any(a>5), np.any(a<0)

(True, False)

In [45]:
np.all(a>5), np.all(a<10)

(False, True)

In [46]:
np.where(a>0, 3, 2) #condition, true일때 3, false일때 2반환 

array([2, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [47]:
a = np.arange(10)
np.where(a>5)

(array([6, 7, 8, 9]),)

In [ ]:
#argmax, argmin